#!/usr/bin/env python3
"""Generate builtin shader C++ sources from a list of GLSL files."""

from __future__ import annotations

import argparse
from pathlib import Path


HEADER_TEXT = """// Generated by scripts/generate_builtin_shaders.py - do not edit.
#pragma once
#include <string_view>
namespace declgl {
enum class ShaderKind { VERT, FRAG };
// Returns the embedded GLSL source for the given (program, kind), or an
// empty string_view if no such builtin is vendored.
std::string_view builtin_shader_source(std::string_view program,
                                       ShaderKind kind);
}  // namespace declgl
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate builtin_shaders.{h,cc} from GLSL inputs."
    )
    parser.add_argument("--shader-dir", required=True, help="Directory containing GLSL files")
    parser.add_argument("--header-out", required=True, help="Path to generated header")
    parser.add_argument("--source-out", required=True, help="Path to generated source")
    parser.add_argument("shader_files", nargs="+", help="Shader file basenames")
    return parser.parse_args()


def parse_shader_name(shader_file: str) -> tuple[str, str]:
    stem = shader_file.removesuffix(".glsl")
    try:
        program, kind_lc = stem.rsplit(".", 1)
    except ValueError as exc:
        raise ValueError(f"Bad shader filename '{shader_file}'") from exc

    if kind_lc == "vert":
        return program, "VERT"
    if kind_lc == "frag":
        return program, "FRAG"
    raise ValueError(f"Bad shader kind '{kind_lc}' for {shader_file}")


def raw_string_delimiter(text: str) -> str:
    base = "DECLGL_SHADER"
    delim = base
    index = 0
    while f"){delim}\"" in text:
        index += 1
        delim = f"{base}_{index}"
    return delim


def render_source(shader_dir: Path, shader_files: list[str]) -> str:
    lines = [
        "// Generated by scripts/generate_builtin_shaders.py - do not edit.",
        '#include "builtin_shaders.h"',
        "#include <string>",
        "#include <unordered_map>",
        "namespace declgl {",
        "namespace {",
        "struct Key {",
        "    std::string program;",
        "    ShaderKind kind;",
        "    bool operator==(const Key& o) const {",
        "        return program == o.program && kind == o.kind;",
        "    }",
        "};",
        "struct KeyHash {",
        "    size_t operator()(const Key& k) const noexcept {",
        "        return std::hash<std::string>{}(k.program) ^ (size_t)k.kind;",
        "    }",
        "};",
        "const std::unordered_map<Key, std::string_view, KeyHash>& table() {",
        "    static const std::unordered_map<Key, std::string_view, KeyHash> t = {",
    ]

    for shader_file in shader_files:
        program, kind = parse_shader_name(shader_file)
        source_text = (shader_dir / shader_file).read_text(encoding="utf-8")
        delim = raw_string_delimiter(source_text)
        lines.append(
            f'        {{ Key{{"{program}", ShaderKind::{kind}}}, '
            f'R"{delim}({source_text}){delim}" }},'
        )

    lines.extend(
        [
            "    };",
            "    return t;",
            "}",
            "}  // namespace",
            "std::string_view builtin_shader_source(std::string_view program, ShaderKind kind) {",
            "    auto& t = table();",
            "    auto it = t.find(Key{std::string(program), kind});",
            "    return it == t.end() ? std::string_view{} : it->second;",
            "}",
            "}  // namespace declgl",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    shader_dir = Path(args.shader_dir).resolve()
    header_out = Path(args.header_out).resolve()
    source_out = Path(args.source_out).resolve()

    header_out.parent.mkdir(parents=True, exist_ok=True)
    source_out.parent.mkdir(parents=True, exist_ok=True)

    header_out.write_text(HEADER_TEXT, encoding="utf-8")
    source_out.write_text(
        render_source(shader_dir, list(args.shader_files)),
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
